baseurl = "http://seananderson.ca"
languageCode = "en-us"
title = "seananderson.ca"
theme = "hugo-sca"
googleAnalytics = "UA-11566420-4"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
rssLimit = 20

[outputs]
  home = [ "HTML", "RSS" ]

[outputFormats]
[outputFormats.RSS]
  mediatype = "application/rss"
  baseName = "feed"

uglyurls = false
enableEmoji = true

[permalinks]
    blog = "/:year/:month/:day/:slug/"

[[menu.main]]
    name = "About"
    url = "/"
    weight = 1
[[menu.main]]
    name = "Blog"
    url = "/blog/"
    weight = 3
[[menu.main]]
    name = "CV"
    url = "/cv/"
    weight = 2
[[menu.main]]
    name = "GitHub"
    url = "https://github.com/seananderson"
    weight = 4
[[menu.main]]
    name = "Workshops"
    url = "/workshops/"
    weight = 5
[[menu.main]]
    name = "Portfolio"
    url = "/portfolio/"
    weight = 6
[[menu.main]]
    name = "Twitter"
    url = "https://twitter.com/sean_anderson"
    weight = 7
[[menu.main]]
    name = "Contact"
    url = "/contact/"
    weight = 8

[params]
    description = ""
    author = "Sean C. Anderson"

    highlightjsVersion = "9.11.0"
    highlightjsCDN = "//cdn.bootcss.com"
    highlightjsLang = ["r", "tex"]
    highlightjsTheme = "github"

    MathJaxCDN = "//cdn.bootcss.com"
    MathJaxVersion = "2.7.1"
